### ISSUE TITLE
Identify the SKU

### ISSUE THREAD

**Issue by perillosantana** [vtex-apps/store-components#402]
**Is your feature request related to a problem? Please describe.**
The `sku-selector` component renders all variations with the same HTML structure, making it impossible to identify a specific variation as a color.

**Describe the solution you'd like**
One way to identify sku and its variations (a class based on the sku name)

**Describe alternatives you've considered**
Develop a proper component to handle SKU selection

**Additional context**
https://github.com/vtex-apps/store-components/blob/279de2e49b1f2008d99615ca93da774c2d96d55c/react/components/SKUSelector/README.md
https://drive.google.com/open?id=1UlFelvoT5U8RBpi9Ydb5mpSjGE7uUXrK

**Comment by rerissondaniel** [comment]
@perillosantana Thanks for opening this issue! I've requested access to the document you provided.

**Comment by rerissondaniel** [comment]
Sorry for the delay, but let me check if I understood your use case:
You would like to identify if a variation is a color or no?
We have a css token `vtex-store-components-3-x-skuSelectorItemImage`. Would it help you if we had a token like `vtex-store-components-3-x-skuSelectorItemColor` ?
Because if we added the sku's name in the token the customization would only work for a specific SKU.

**Comment by perillosantana** [comment]
@rerissondaniel In this case it would solve, because I need to identify the color, but in other scenarios it would be good to be able to identify any specification

**Comment by rerissondaniel** [comment]
So maybe a solution was to use the variation name as a class. I'm gonna discuss with the team if there's any downsides in that and add it to our backlog. Thanks for your patience and time
