### ISSUE TITLE
Add to Cart button border-radius 

### ISSUE THREAD

**Issue by cristian-milea** [vtex-apps/store-components#702]
**Describe the bug**
setting border-radius on a `vtex-add-to-cart-button` doesn't work

**To Reproduce**
```
// vtex.add-to-cart-button.css
.buttonDataContainer {
  border-radius: 20px;
}
```

**Expected behavior**
should have a css handler for setting border on the button, not the div inside it

**Desktop (please complete the following information):**
 - OS: [MacOS 10.15.3]
 - Browser [Safari]
 - Version [13.0.5]

**Additional context**
Want to set all buttons site-wide to have border-radius 20px

**Comment by klzns** [comment]
You can achieve that by changing this value:
https://github.com/vtex-apps/store-theme/blob/master/styles/configs/style.json#L243

This will affect all instances of border radius Tachyons classes:

![image](https://user-images.githubusercontent.com/284515/74342130-c2106700-4d87-11ea-8f7e-d2a84ba4b689.png)

**Comment by cristian-milea** [comment]
This is not ideal. It also changes all `br2` tachyon usages for vtex-input-prefix__group (the search container)

**Comment by klzns** [comment]
Can you print the HTML element you are trying to target?

**Comment by cristian-milea** [comment]
i want to make all buttons have certain radius, paddings, and font sizes without affecting other elements

`
<button tabindex="0" class="vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-regular t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100 " type="button"><div class="vtex-button__label flex items-center justify-center h-100 ph6 w-100 border-box " style="padding-top:.25em;padding-bottom:.32em"><div class="vtex-add-to-cart-button-0-x-buttonDataContainer flex justify-center"><span class="vtex-add-to-cart-button-0-x-buttonText">Adaugă în coș</span></div></div></button>
`

**Comment by klzns** [comment]
In fact, this handle doesn't target the button element. To achieve this you can wrap the buy button with a flex-layout with a blockClass:

```json
  "flex-layout.row#buy-button": {
    "props": {
      "blockClass": "buyButton",
      "marginTop": 4,
      "marginBottom": 7
    },
    "children": ["buy-button"]
  },
```

Then in `styles/css/vtex.flex-layout.css` target the button with the allowed `:global(.vtex-` selector:

```css
.flexRow--buyButton :global(.vtex-button) {
  border-radius: 10px;
}
```

You can see that it worked:
![image](https://user-images.githubusercontent.com/284515/74476076-6d541580-4e87-11ea-94b2-b229c81266d8.png)
![image](https://user-images.githubusercontent.com/284515/74476106-76dd7d80-4e87-11ea-87f2-a48cda6b2ff2.png)



About font on buttons, it might make sense to change the typography tokens related to buttons:
https://github.com/vtex-apps/store-theme/blob/master/styles/configs/style.json#L318-L337

More on this here: https://styleguide.vtex.com/#/Styles?id=section-typography#action

**Comment by cristian-milea** [comment]
That means we have to wrap ALL my buy buttons everywhere in the site and it is cumbersome.
Why isn't Vtex exposing the buy-button with a css handle as all the other components?

**Comment by klzns** [comment]
I totally agree with you that's **not** the ideal 💯 

But our BuyButton component was implemented in a way that it uses the Styleguide's Button component as the root component and our Styleguide was not implemented with CSS Handles or Store Framework in mind since it's development started before Store Framework.

We could add a `<div>` wrapping the Styleguide's Button making the BuyButton component to be something like:

```html
<div class="vtex-store-components-2-x-buyButton">
  <button class="vtex-button" />
  ...
```

But this change would break stores that are customizing the CSS with hierarchical HTML structure in mind. Example:

```css
.flex-layout--buyButton > button {
  border-radius: 10px;
}
```

A store with this CSS would break its layout when we added this new `div` element because now the button is not a direct child of `.flex-layout--buyButton` (and that's why the styles v2 limitations was put in place).

The solution I proposed it's a workaround to the current limitations.

We intend to solve this in a new major version of this block 🙏
